#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define TARGET 3675
#define iCap 10

task main()
{
	float k = 0.01;
	int error = 0;
	int pasterror;

	while(true){
		error = TARGET - SensorValue[pot];
		//power = pasterror * k
		motor[port1] = k * error;
		pasterror += error;
		wait1Msec(25);

		if(pasterror < iCap){
			pasterror = -iCap;
			}

	}


}
