#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightdrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightdrive2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftleft1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftright1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mobleft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mobright,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();

		//I started coding from here...

		//CODE FOR THE DRIVE

		//The right side of the joystick controlls the right side of the robot, y-axis
		motor[rightdrive1] = vexRT[Ch2];
		motor[rightdrive1] = vexRT[Ch2];
		//The left side of the joystick controlls the left side of the robot, y-axis
		motor[leftdrive1] = vexRT[Ch3];
		motor[leftdrive1] = vexRT[Ch3];

		//right side down and right are mogo
		//left side autostack
		//left side claw
		//right side lift sytem(+ left side
		//towards center

		//MOBILE GOAL INTAKE SYSTEM
		if (vexRT[Btn8R] == 1)//move out of robot
		{
			motor[mobleft] = 127;
			motor[mobright] = 127;
		}else if (vexRT[Btn8D] == 1)//move into robot
		{
			motor[mobleft] = -127;
			motor[mobright] = -127;
		}else
		{
			motor[mobleft] = 0;
			motor[mobright] = 0;
		}

		//CLAW
		if (vexRT[Btn5U] == 1) //claw opens
		{
			motor[claw] = 127;
		}else if (vexRT[Btn5D] == 1)
		{
			motor[claw] = -127; //claw closes
		}else
		{
			motor[claw] = 0;


			//BASE LIFT SYSTEM
			if (vexRT[Btn6U] == 1)//joystick controlls base lift
			{
				//move base lift up
				motor[lift2] = 127;

			}else if (vexRT[Btn6D] == 1)
			{
				//move base lift down
				motor[lift2] = -127;
			}else
			{
				motor[lift2] = 0;
			}

			//UPPER LIFT SYSTEM
			if (vexRT[Btn7R] == 1)//joystick controlls upper lift
			{
				//move upper four bar up
				motor[liftleft1] = 127;
				motor[liftright1] = 127;
			}else if (vexRT[Btn7D] == 1)
			{
				//move upper four bar down
				motor[liftleft1] = -127;
				motor[liftright1] = -127;
			}else
			{
				motor[liftleft1] = 0;
				motor[liftright1] = 0;
			}


		}
	}

}
