#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontleft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontright,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backright,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// int x =SensorValue[encoder]
// if (x == 1272){ motor[port2] = 0; motor[port3] = 0;motor[port4] = 0;motor[port5] = 0;}
//else if (x < 1272) { motor[port2] = 0; motor[port3] = 0;motor[port4] = 0;motor[port5] = 0;}
//5 to 7 encoder to wheel

task main()
{
	int x = SensorValue[encoder];

	while(true){

		if (x == 1272)
		{
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port4] = 0;
			motor[port5] = 0;
		}
		else if (x < 1272)
		{
			motor[port2] = 127;
			motor[port3] = 127;
			motor[port4] = 127;
			motor[port5] = 127;
		}


	}
