#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightdrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightdrive2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftleft1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftright1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mobleft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mobright,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void allMovForward (int speed, int time)
{
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;

	wait1Msec(time);
}

void stopDriveMotors ()
{
	motor[leftdrive1] = 0;
	motor[rightdrive2] = 0;
	motor[leftdrive1] = 0;
	motor[rightdrive2] = 0;
}

void allMovBackward (int speed, int time)
{
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;

	wait1Msec(time);
}

void turnPtRight (int speed, int time)
{
	motor[rightdrive1] = -speed;
	motor[rightdrive2] = -speed;
	motor[leftdrive1] = speed;
	motor[leftdrive2] = speed;
	wait1Msec(time);
}

void turnPtLeft (int speed, int time)
{
	motor[leftdrive1] = -speed;
	motor[leftdrive2] = -speed;
	motor[rightdrive1] = speed;
	motor[rightdrive2] = speed;
	wait1Msec(time);
}

void turnSwForward (int speed, int time, int direction)//turning robot foward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = speed;
		motor[leftdrive2] = speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = speed;
		motor[rightdrive2] = speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}

void turnSwBackward (int speed, int time, int direction)//turning robot backward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = -speed;
		motor[leftdrive2] = -speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = -speed;
		motor[rightdrive2] = -speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}
/* Another way of doing swing turns

void turnSwRight (int speed, int time, bool direction)//right drive stays put and left drive moves either forward or backward
{
if (bool direction == true){ //moves forward
motor[leftdrive1] = speed;
motor[leftdrive2] = speed;
motor[rightdrive1] = 0;
motor[rightdrive2] = 0;
wait1Msec(time);
}
if (bool direction == false){//moves backward
motor[leftdrive1] = -speed;
motor[leftdrive2] = -speed;
motor[rightdrive1] = 0;
motor[rightdrive2] = 0;
wait1Msec(time);
}
}

void turnSwLeft (int speed, int time, bool direction)//left drive stays put and right drive moves either forward or backward
{
if (bool direction == true){ //moves forward
motor[rightdrive1] = speed;
motor[rightdrive2] = speed;
motor[leftdrive1] = 0;
motor[leftdrive2] = 0;
}
if (bool direction == false){ //moves backward
motor[rightdrive1] = -speed;
motor[rightdrive2] = -speed;
motor[leftdrive1] = 0;
motor[leftdrive2] = 0;
}
}
*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();

	//trying auton for red side(right side/long side)

	wait1Msec(25);
	allMovForward(127,2500);
	//stop when picking up mobile goal
	stopDriveMotors();
	wait1Msec(3500);
	//moving mobile goal into robot
	motor[mobleft] = -127;;
	motor[mobright] = 127;
	//move backward
	allMovBackward(127,2250);
	//lift the lift system up to make sure that it does not hit the wall when turning(next step)
	motor[liftleft1] = 127;
	motor[liftright1] = 127;
	wait1Msec(750);
	//turn to face parallel to rods
	turnPtLeft(75,1000);
	//move foward to middle of zone
	allMovForward(127, 1250);
	//turn to face perpendicular to rods
	turnPtLeft(127, 1000);
	//time to enter scoring zone
	allMovForward(127, 1750);//arrive in front of 20 pt zone
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(1500);//drop mobile cone at this step
	//it has been 15525 one-thousandths of a second(15 sec)
	allMovBackward(127, 1000);//release cone by going back(the mobile goal must be lifted while going back simultaneously)



}
task autonomous()//lower lift sytstem for stability when entering scoring zone
{
	wait1Msec(12275);//it took 12275 one thousandth of a second(12 sec) so far to reach scoring zone
	wait1Msec(500);//move forward a bit so robot doesn't hit the stationary goal
	motor[liftleft1] = -127;
	motor[liftright1] = -127;
	wait1Msec(750);

}

task autonomous() //lifts mobile goal lift sytem letting the mobile goal to slide into scoring zone at the end of the auton
{
	wait1Msec(15525);
	motor[mobleft] = -127;
	motor[mobright] = -127;
	wait1Msec(1000);
}

task autonomous()
{
	wait1Msec(25);
	motor[liftleft1] = 63;
	motor[liftright1] = 63;
	wait1Msec(2000);
}

task autonomous()
{
	wait1Msec(525);
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(3000);
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task usercontrol()
{
	// User control code here, inside the loop
	wait1Msec(2000);

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();

		//I started coding from here...

		//The right side of the joystick controlls the right side of the robot, y-axis
		motor[rightdrive1] = vexRT[Ch2];
		motor[rightdrive1] = vexRT[Ch2];
		//The left side of the joystick controlls the left side of the robot, y-axis
		motor[leftdrive1] = vexRT[Ch3];
		motor[leftdrive1] = vexRT[Ch3];

		if (vexRT[Btn6U] == 1)//joystick controlls claw
		{
			motor[claw] = 127;
		}else if (vexRT[Btn6D] == 1)
		{
			motor[claw] = -127;
		}else
		{
			motor[claw] = 0;
		}

		if (vexRT[Btn8U] == 1)//joystick controlls upper lift
		{
			motor[liftleft1] = -127;
			motor[liftright1] = -127;
		}else if (vexRT[Btn8D] == 1)
		{
			motor[liftleft1] = 127;
			motor[liftright1] = 127;
		}else
		{
			motor[liftleft1] = 0;
			motor[liftright1] = 0;
		}

		if (vexRT[Btn5U] == 1)//joystick controlls base lift
		{
			motor[lift2] = -127;
		}else if (vexRT[Btn5D] == 1)
		{
			motor[lift2] = 127;
		}else
		{
			motor[lift2] = 0;
		}



	}
}
