#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdrive1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftdrive2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightdrive1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightdrive2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mobleft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mobright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          liftleft1,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


//NOTE: BOTH SETS OF LIFT MOTORS ARE GOING INTO SAME PORTS

//reset button
//auto stack lifts system up by a certain

//right side down and right are mogo
//left side autostack
//left side claw
//right side lift sytem(+ left side
//towards center

//Forward references for functions
task stepOne();
task stepTwo();
task stepThree();
task stepFour();

//defining variables
int p;
int n;
int c;
int d;

int l;
int m;
int a;

//auton functions

void powerDrive (int leftspeed, int rightspeed)
{
	motor[leftdrive1] = leftspeed;
	motor[leftdrive2] = leftspeed;
	motor[rightdrive1] = rightspeed;
	motor[rightdrive2] = rightspeed;
}

void allMovForward (int speed, int time)
{
	powerDrive(speed, speed);
	wait1Msec(time);
}

void stopDriveMotors ()
{
	powerDrive(0, 0);
}

void allMovBackward (int speed, int time)
{
	powerDrive(-speed, -speed);
	wait1Msec(time);
}
//adding
//decrement
//reset
//pinnning-block a robot from

void turnPtRight (int speed, int time)
{
	powerDrive(speed, -speed); //remember that
	wait1Msec(time);
}

//takes about 28.8 inch distance to turn in the auton
//this is about 2.82 rotations, or 1015 ticks
void turnPtLeft (int encoderValue, int speed)
{
	while (SensorValue[rightEncoder] < encoderValue) {
		powerDrive(-speed, speed);
	}
}

/*void turnPtLeft (int speed, int time)
{
powerDrive(-speed, speed);
wait1Msec(time);
} */

void turnSwForward (int speed, int time, int direction)//turning robot foward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = speed;
		motor[leftdrive2] = speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = speed;
		motor[rightdrive2] = speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}

void turnSwBackward (int speed, int time, int direction)//turning robot backward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = -speed;
		motor[leftdrive2] = -speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = -speed;
		motor[rightdrive2] = -speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}
/* Another way of doing swing turns

void turnSwRight (int speed, int time, bool direction)//right drive stays put and left drive moves either forward or backward
{
if (bool direction == true){ //moves forward
motor[leftdrive1] = speed;
motor[leftdrive2] = speed;
motor[rightdrive1] = 0;
motor[rightdrive2] = 0;
wait1Msec(time);
}
if (bool direction == false){//moves backward
motor[leftdrive1] = -speed;
motor[leftdrive2] = -speed;
motor[rightdrive1] = 0;
motor[rightdrive2] = 0;
wait1Msec(time);
}
}

void turnSwLeft (int speed, int time, bool direction)//left drive stays put and right drive moves either forward or backward
{
if (bool direction == true){ //moves forward
motor[rightdrive1] = speed;
motor[rightdrive2] = speed;
motor[leftdrive1] = 0;
motor[leftdrive2] = 0;
}
if (bool direction == false){ //moves backward
motor[rightdrive1] = -speed;
motor[rightdrive2] = -speed;
motor[leftdrive1] = 0;
motor[leftdrive2] = 0;
}
}
*/


//TASKS USED IN AUTON

task stepFour() //lifts mobile goal lift sytem letting the mobile goal to slide into scoring zone at the end of the auton
{
	//wait1Msec(15525); 4th
	wait1Msec(25);
	motor[mobleft] = -127;
	motor[mobright] = -127;
	wait1Msec(1000);
}

task stepOne()
{
	wait1Msec(25); //1st
	motor[liftleft1] = 63;
	//motor[liftright1] = 63;
	wait1Msec(2000);
}

task stepTwo()
{
	//wait1Msec(525); 2st
	wait1Msec(525);
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(3000);
}

task stepThree()//lower lift sytstem for stability when entering scoring zone
{
	//wait1Msec(12275);//it took 12275 one thousandth of a second(12 sec) so far to reach scoring zone 3rd
	wait1Msec(500);//move forward a bit so robot doesn't hit the stationary goal
	motor[liftleft1] = -127;
	motor[liftright1] = -127;
	wait1Msec(750);

}

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();


	//the values for the encoders are listed below

	//fist estimate is 2592 inches and 7.2 revolutions
	//field 144 by 144 inches
	//diameter 3.25
	//one revolution is 10.21 inches
	//half the distance of field is = a little more than the distance from the rod to the mogo = distance from corner to stationary goal
	//distance from robot original position to position in front of mogo times 3 and a 1/2 is the length of the whole field
	//this is 41.14 inches
	//so second estimate is 4 revolutions and
	//1440 ticks
	//to go into zone = 24 inches and 2.4 revolutions
	//thus 864 ticks
	//to get over the rods add another 1 revolution
	//therefore 1224 ticks

	p = 1440;
	n = p - 1440;
	l = 1015 + n;
	m = l + 270;
	a = m + 1200;
	c = m + 1224;
	d = c - 600;


	//the following are tasks used in the auton




	//auton code with encoders begins here

	//PART 1: GO AND PICK UP THE MOBILE GOAL AND PLACE IT IN THE ROBOT

	wait1Msec(25);
	//the lift sytem moves up while
	startTask(stepOne);
	//the mobile goal intake moves outward while
	startTask(stepTwo);

	//from the starting postition next to the rods the robot moves forward to mobogo until it reaches it
	while (SensorValue[rightEncoder] < p && SensorValue[leftEncoder] < p)
	{
		powerDrive(127, 127);
	}

	//stop the drive when picking up mobile goal
	stopDriveMotors();
	wait1Msec(3500);
	//move mobile goal into robot
	motor[mobleft] = -127;
	motor[mobright] = 127;

	//PART 2: MOVE TOWARDS THE ZONE

	//move backward to around starting position
	while (SensorValue[rightEncoder] < n && SensorValue[leftEncoder] < n )
	{
		powerDrive(-127, -127);
	}

	//lift the lift system up to make sure that it does not hit the wall when turning(next step)
	motor[liftleft1] = 127;
	motor[liftright1] = 127;
	wait1Msec(750);

	//turn to face parallel to rods
	turnPtLeft(l, 75);
	startTask(stepThree);
	//NEED TO USE ENCODERS HERE
	//move foward to middle of zone
	//allMovForward(127, 1250);
	while (SensorValue[rightEncoder] < a) {
		powerDrive(127, 127);
	}
	//turn to face perpendicular to rods
	turnPtLeft(m, 127);

	//PART 3: MOVE INTO THE ZONE, TAKE MOBILE GOAL OUT OF ROBOT, AND DROP THE MOBILE GOAL IN 20 PT ZONE WHEN MOVING BACKWARD

	//move lift system up while
	startTask(stepFour);

	//moving forward into zone
	while (SensorValue[rightEncoder] < c && SensorValue[leftEncoder] < c )
	{
		powerDrive(127, 127);
	}

	//mobile intake system moves out
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(1500);
	//it has been 15525 one-thousandths of a second(15 sec)


	//NEED A TASK HERE TO LOWER MOBILE GOAL INTAKE WHILE MOVING BACK
	//move backward away from zone releasing the mobile goal
	while (SensorValue[rightEncoder] < d && SensorValue[leftEncoder] < d )
	{
		powerDrive(-127, -127);
	}







	//CODE WITHOUT ENCODERS
	//trying auton for red side(right side/long side)

	wait1Msec(25);
	startTask(stepOne);
	startTask(stepTwo);
	allMovForward(127,2500);
	//stop when picking up mobile goal
	stopDriveMotors();
	wait1Msec(3500);
	//moving mobile goal into robot
	motor[mobleft] = -127;
	motor[mobright] = 127;
	//move backward
	allMovBackward(127,2250);
	//lift the lift system up to make sure that it does not hit the wall when turning(next step)
	motor[liftleft1] = 127;
	motor[liftright1] = 127;
	wait1Msec(750);

	//turn to face parallel to rods
	turnPtLeft(l, 75);
	startTask(stepThree);
	//move foward to middle of zone
	allMovForward(127, 1250);
	//turn to face perpendicular to rods
	turnPtLeft(m, 127);
	//time to enter scoring zone
	startTask(stepFour);
	allMovForward(a, 127);//arrive in front of 20 pt zone
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(1500);//drop mobile cone at this step
	//it has been 15525 one-thousandths of a second(15 sec)
	allMovBackward(127, 1000);//release cone by going back(the mobile goal must be lifted while going back simultaneously)

}




/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task usercontrol()
{
	// User control code here, inside the loop
	wait1Msec(2000);

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();

		//I started coding from here...

		//The right side of the joystick controlls the right side of the robot, y-axis
		motor[rightdrive1] = vexRT[Ch2];
		motor[rightdrive1] = vexRT[Ch2];
		//The left side of the joystick controlls the left side of the robot, y-axis
		motor[leftdrive1] = vexRT[Ch3];
		motor[leftdrive1] = vexRT[Ch3];

		//right side down and right are mogo
		//left side autostack
		//left side claw
		//right side lift sytem(+ left side
		//towards center

		//mobile goal code
		if (vexRT[Btn8R] == 1)//move out of robot
		{
			motor[mobleft] = 127;
			motor[mobright] = 127;
		}else if (vexRT[Btn8D] == 1)//move into robot
		{
			motor[mobleft] = -127;
			motor[mobright] = -127;
		}else
		{
			motor[mobleft] = 0;
			motor[mobright] = 0;
		}

		//claw code
		if (vexRT[Btn5U] == 1) //claw opens
		{
			motor[claw] = 127;
		}else if (vexRT[Btn5D] == 1)
		{
			motor[claw] = -127; //claw closes
		}else
		{
			motor[claw] = 0;

			if (vexRT[Btn6U] == 1)//joystick controlls base lift
			{
				//move base lift up
				motor[lift2] = 127;

			}else if (vexRT[Btn6D] == 1)
			{
				//move base lift down
				motor[lift2] = -127;
			}else
			{
				motor[lift2] = 0;
			}

			if (vexRT[Btn7R] == 1)//joystick controlls upper lift
			{
				//move upper four bar up
				motor[liftleft1] = 127;
				motor[liftright1] = 127;
			}else if (vexRT[Btn7D] == 1)
			{
				//move upper four bar down
				motor[liftleft1] = -127;
				motor[liftright1] = -127;
			}else
			{
				motor[liftleft1] = 0;
				motor[liftright1] = 0;
			}
		if (vexRt[Btn7U] == 1)
		{

		}

		}
	}
}
