#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightdrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightdrive2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftleft1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftright1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mobleft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mobright,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void allMovForward (int speed, int time)
{
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;

	wait1Msec(time);
}

void allMovBackward (int speed, int time)
{
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;
	motor[leftdrive1] = speed;
	motor[rightdrive2] = speed;

	wait1Msec(time);
}

void turnPtRight (int speed, int time)
{
	motor[rightdrive1] = -speed;
	motor[rightdrive2] = -speed;
	motor[leftdrive1] = speed;
	motor[leftdrive2] = speed;
	wait1Msec(time);
}

void turnPtLeft (int speed, int time)
{
	motor[leftdrive1] = -speed;
	motor[leftdrive2] = -speed;
	motor[rightdrive1] = speed;
	motor[rightdrive2] = speed;
	wait1Msec(time);
}

void turnSwForward (int speed, int time, int direction)//turning robot foward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = speed;
		motor[leftdrive2] = speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = speed;
		motor[rightdrive2] = speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}

void turnSwBackward (int speed, int time, int direction)//turning robot foward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = -speed;
		motor[leftdrive2] = -speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = -speed;
		motor[rightdrive2] = -speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}
/* Another way of doing swing turns

void turnSwRight (int speed, int time, bool direction)//right drive stays put and left drive moves either forward or backward
{
	if (bool direction == true){ //moves forward
		motor[leftdrive1] = speed;
		motor[leftdrive2] = speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (bool direction == false){//moves backward
		motor[leftdrive1] = -speed;
		motor[leftdrive2] = -speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
}

void turnSwLeft (int speed, int time, bool direction)//left drive stays put and right drive moves either forward or backward
{
	if (bool direction == true){ //moves forward
		motor[rightdrive1] = speed;
		motor[rightdrive2] = speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
	}
	if (bool direction == false){ //moves backward
		motor[rightdrive1] = -speed;
		motor[rightdrive2] = -speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
	}
}
*/


task usercontrol()
{
	// User control code here, inside the loop
	wait1Msec(2000);

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();

		//I started coding from here...

		//The right side of the joystick controlls the right side of the robot, y-axis
		motor[rightdrive1] = vexRt[Ch2];
		motor[rightdrive1] = vexRt[Ch2];
		//The left side of the joystick controlls the left side of the robot, y-axis
		motor[leftdrive1] = vexRt[Ch3];
		motor[leftdrive1] = vexRt[Ch3];
	}
}
