#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdrive1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftdrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightdrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightdrive2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mobleft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mobright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,          liftleft1,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


//Forward references for functions
task stepOne();
task stepTwo();
task stepThree();
task stepFour();

//auton functions

void powerDrive (int leftspeed, int rightspeed)
{
	motor[leftdrive1] = leftspeed;
	motor[leftdrive2] = leftspeed;
	motor[rightdrive1] = rightspeed;
	motor[rightdrive2] = rightspeed;
}

void allMovForward (int speed, int time)
{
	powerDrive(speed, speed);
	wait1Msec(time);
}

void stopDriveMotors ()
{
	powerDrive(0, 0);
}

void allMovBackward (int speed, int time)
{
	powerDrive(-speed, -speed);
	wait1Msec(time);
}
//adding
//decrement
//reset
//pinnning-block a robot from

void turnPtRight (int speed, int time)
{
	powerDrive(-speed, speed); //remember that
	wait1Msec(time);
}

//takes about 28.8 inch distance to turn in the auton
//this is about 2.82 rotations, or 1015 ticks

void turnPtLeft (int speed, int time)
{
powerDrive(speed, -speed);
wait1Msec(time);
}

void turnSwForward (int speed, int time, int direction)//turning robot foward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = speed;
		motor[leftdrive2] = speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = speed;
		motor[rightdrive2] = speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}

void turnSwBackward (int speed, int time, int direction)//turning robot backward with one drive fixed and the other drive forward
{
	if (direction == 1){ //moves right
		motor[leftdrive1] = -speed;
		motor[leftdrive2] = -speed;
		motor[rightdrive1] = 0;
		motor[rightdrive2] = 0;
		wait1Msec(time);
	}
	if (direction == 0){//moves left
		motor[rightdrive1] = -speed;
		motor[rightdrive2] = -speed;
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		wait1Msec(time);
	}
}
/* Another way of doing swing turns
void turnSwRight (int speed, int time, bool direction)//right drive stays put and left drive moves either forward or backward
{
if (bool direction == true){ //moves forward
motor[leftdrive1] = speed;
motor[leftdrive2] = speed;
motor[rightdrive1] = 0;
motor[rightdrive2] = 0;
wait1Msec(time);
}
if (bool direction == false){//moves backward
motor[leftdrive1] = -speed;
motor[leftdrive2] = -speed;
motor[rightdrive1] = 0;
motor[rightdrive2] = 0;
wait1Msec(time);
}
}
void turnSwLeft (int speed, int time, bool direction)//left drive stays put and right drive moves either forward or backward
{
if (bool direction == true){ //moves forward
motor[rightdrive1] = speed;
motor[rightdrive2] = speed;
motor[leftdrive1] = 0;
motor[leftdrive2] = 0;
}
if (bool direction == false){ //moves backward
motor[rightdrive1] = -speed;
motor[rightdrive2] = -speed;
motor[leftdrive1] = 0;
motor[leftdrive2] = 0;
}
}
*/


//TASKS USED IN AUTON

task stepFour() //lifts mobile goal lift sytem letting the mobile goal to slide into scoring zone at the end of the auton
{
	//wait1Msec(15525); 4th
	wait1Msec(25);
	motor[mobleft] = -127;
	motor[mobright] = -127;
	wait1Msec(1000);
}

task stepOne()
{
	wait1Msec(25); //1st
	motor[liftleft1] = 63;
	//motor[liftright1] = 63;
	wait1Msec(2000);
}

task stepTwo()
{
	//wait1Msec(525); 2st
	wait1Msec(525);
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(3000);
}

task stepThree()//lower lift sytstem for stability when entering scoring zone
{
	//wait1Msec(12275);//it took 12275 one thousandth of a second(12 sec) so far to reach scoring zone 3rd
	wait1Msec(500);//move forward a bit so robot doesn't hit the stationary goal
	motor[liftleft1] = -127;
	wait1Msec(750);

}

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	//AutonomousCodePlaceholderForTesting();


	//CODE WITHOUT ENCODERS
	//trying auton for red side(right side/long side) and I believe blue right side

	wait1Msec(25);
	startTask(stepTwo);
	allMovForward(127,2500);
	//moving mobile goal into robot
	motor[mobleft] = -127;
	motor[mobright] = 127;
	wait1Msec(2000);
	//move backward
	allMovBackward(127,2250);

	//turn to face parallel to rods
	turnPtLeft(127, 2000);
	startTask(stepThree);
	//move foward to middle of zone
	allMovForward(127, 1250);
	//turn to face perpendicular to rods
	turnPtLeft(1250, 127);
	allMovForward(2500, 127);//arrive in front of 20 pt zone
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(1500);//drop mobile cone at this step
	//it has been 15525 one-thousandths of a second(15 sec)
	allMovBackward(127, 1000);//release cone by going back(the mobile goal must be lifted while going back simultaneously)
	startTask(stepFour);



	/*

	//auton for left auton for red and blue sides

	wait1Msec(25);
	startTask(stepTwo);
	allMovForward(127,2500);
	//moving mobile goal into robot
	motor[mobleft] = -127;
	motor[mobright] = 127;
	wait1Msec(2000);
	//move backward
	allMovBackward(127,2250);
	//turn to face parallel to rods
	rightPtLeft(127, 2000);
	startTask(stepThree);
	//move foward to middle of zone
	allMovForward(127, 1250);
	//turn to face perpendicular to rods
	rightPtLeft(1250, 127);
	allMovForward(2500, 127);//arrive in front of 20 pt zone
	motor[mobleft] = 127;
	motor[mobright] = 127;
	wait1Msec(1500);//drop mobile cone at this step
	//it has been 15525 one-thousandths of a second(15 sec)
	allMovBackward(127, 1000);//release cone by going back(the mobile goal must be lifted while going back simultaneously)
	startTask(stepFour);

	*/

}




/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task usercontrol()
{
	// User control code here, inside the loop
	wait1Msec(2000);

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();

		//I started coding from here...

		//The right side of the joystick controlls the right side of the robot, y-axis
		motor[rightdrive1] = vexRT[Ch2];
		motor[rightdrive2] = vexRT[Ch2];
		//The left side of the joystick controlls the left side of the robot, y-axis
		motor[leftdrive1] = vexRT[Ch3];
		motor[leftdrive2] = vexRT[Ch3];

		//right side down and right are mogo
		//left side autostack
		//left side claw
		//right side lift sytem(+ left side
		//towards center

		//mobile goal code
		if (vexRT[Btn8U] == 1)//move out of robot
		{
			motor[mobleft] = 127;
			motor[mobright] = 127;
		}else if (vexRT[Btn8D] == 1)//move into robot
		{
			motor[mobleft] = -127;
			motor[mobright] = -127;
		}else
		{
			motor[mobleft] = 0;
			motor[mobright] = 0;
		}

		//claw code
		/*if (vexRT[Btn5U] == 1) //claw opens
		{
			motor[claw] = 127;
		}else if (vexRT[Btn5D] == 1)
		{
			motor[claw] = -127; //claw closes
		}else
		{
		motor[claw] = 0; //claw does nothing if nothing is pressed
		}
		
		if (vexRT[Btn6U] == 1)//joystick controlls base lift
			{
				//move base lift up
				motor[lift2] = 127;
				motor[liftleft1] = 127;
			
			}else if (vexRT[Btn6D] == 1)
			{
				//move base lift down
				motor[lift2] = -127;
				motor[liftleft1] = -127;
			}else
			{
				motor[lift2] = 0;
				motor[liftleft1] = 0;
			}
			/* (vexRT[Btn7U] == 1)//joystick controlls upper lift
			{
				//move upper four bar up
				motor[liftleft1] = 127;
				motor[liftright1] = 127;
			}else if (vexRT[Btn7D] == 1)
			{
				//move upper four bar down
				motor[liftleft1] = -127;
				motor[liftright1] = -127;
			}else
			{
				motor[liftleft1] = 0;
				motor[liftright1] = 0;
			}
		//if (vexRt[Btn7U] == 1)
		//{
		//}
*/
		}
	}
